# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamRangeproofData(p.MessageType):
    MESSAGE_WIRE_TYPE = 913

    def __init__(
        self,
        data_taux: bytes = None,
        is_successful: bool = None,
    ) -> None:
        self.data_taux = data_taux
        self.is_successful = is_successful

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('data_taux', p.BytesType, 0),
            2: ('is_successful', p.BoolType, 0),
        }
