# Automatically generated by pb2py
# fmt: off
import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamCoinID(p.MessageType):

    def __init__(
        self,
        idx: int = None,
        type: int = None,
        sub_idx: int = None,
        amount: int = None,
        asset_id: int = None,
    ) -> None:
        self.idx = idx
        self.type = type
        self.sub_idx = sub_idx
        self.amount = amount
        self.asset_id = asset_id

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('idx', p.UVarintType, 0),
            2: ('type', p.UVarintType, 0),
            3: ('sub_idx', p.UVarintType, 0),
            4: ('amount', p.UVarintType, 0),
            5: ('asset_id', p.UVarintType, 0),
        }
