# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .BeamSignTransactionSplit import BeamSignTransactionSplit

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamSignTransactionSplitResult(p.MessageType):

    def __init__(
        self,
        tx: BeamSignTransactionSplit = None,
    ) -> None:
        self.tx = tx

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('tx', BeamSignTransactionSplit, 0),
        }
