# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamGetPKdf(p.MessageType):
    MESSAGE_WIRE_TYPE = 925

    def __init__(
        self,
        is_root_key: bool = None,
        child_idx: int = None,
        show_display: bool = None,
    ) -> None:
        self.is_root_key = is_root_key
        self.child_idx = child_idx
        self.show_display = show_display

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('is_root_key', p.BoolType, 0),
            2: ('child_idx', p.UVarintType, 0),
            3: ('show_display', p.BoolType, 0),
        }
