# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .BeamCoinID import BeamCoinID

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamCreateOutput(p.MessageType):
    MESSAGE_WIRE_TYPE = 927

    def __init__(
        self,
        coin_id_scheme: int = None,
        coin_id: BeamCoinID = None,
    ) -> None:
        self.coin_id_scheme = coin_id_scheme
        self.coin_id = coin_id

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('coin_id_scheme', p.UVarintType, 0),
            2: ('coin_id', BeamCoinID, 0),
        }
