# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .BeamECCPoint import BeamECCPoint

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamPKdf(p.MessageType):
    MESSAGE_WIRE_TYPE = 926

    def __init__(
        self,
        key: bytes = None,
        cofactor_G: BeamECCPoint = None,
        cofactor_J: BeamECCPoint = None,
    ) -> None:
        self.key = key
        self.cofactor_G = cofactor_G
        self.cofactor_J = cofactor_J

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('key', p.BytesType, 0),
            2: ('cofactor_G', BeamECCPoint, 0),
            3: ('cofactor_J', BeamECCPoint, 0),
        }
