# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .BeamTxCommon import BeamTxCommon
from .BeamTxMutualInfo import BeamTxMutualInfo

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class BeamSignTransactionReceive(p.MessageType):
    MESSAGE_WIRE_TYPE = 919

    def __init__(
        self,
        tx_common: BeamTxCommon = None,
        tx_mutual_info: BeamTxMutualInfo = None,
    ) -> None:
        self.tx_common = tx_common
        self.tx_mutual_info = tx_mutual_info

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('tx_common', BeamTxCommon, 0),
            2: ('tx_mutual_info', BeamTxMutualInfo, 0),
        }
